TEST-#15: Add get_history and apply_history tests
modin-project/qgrid pull request #17
Opened 2021-03-03 21:20 UTC by valerieyip

## What do these changes do?

- Fixes bugs with record transformation
- Adds tests for get_history and apply_history
- Also resolves https://github.com/modin-project/qgrid/issues/16

- [X] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [] passes `flake8 .`
- [X] passes `black --check .`
- [X] signed commit with `git commit -s` 
- [X] Resolves #15  ? 
- [X] tests added and passing

2021-03-03 21:35 UTC, devin-petersohn requested changes
@valerieyip I think you accidentally added a lot of unnecessary files, would you be able to check?

2021-03-04 20:58 UTC, richardlin047 requested changes
File deletion looks good, just some minor edits.

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/grid.py
> +            # self._view_msgs.append(content)
Get rid of comment

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    # EDIT_CELL
Nit: Change to lowercase e.g. `# Edit cell`

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    # REMOVE_ROW
Same with the rest.

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    # CHANGE_SELECTION
Add comment saying that you don't expect history to change. Same with Change viewport.

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    changed_df = spreadsheet.get_changed_df()
Add assert that df_copy doesn't equal changed df.

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +    another_df = df.copy()
Rename to df_copy

2021-03-04 20:58 UTC, richardlin047 commented on modin_spreadsheet/tests/test_grid.py
> +        {"type": "change_sort", "sort_field": "Date", "sort_ascending": True}
Keep consistent with spacing between functions.

2021-03-06 00:29 UTC, richardlin047 requested changes
Think you forgot to commit the update_table functional call in the edit_cell logic section. Please add `self._update_table(triggered_by="edit_cell", fire_data_change_event=True)` to line 1528 in grid.py.

2021-03-12 16:56 UTC, richardlin047 approved these changes
Verified that it resolves #16, resolves #18.

@devin-petersohn let me know if you would like to review or if I should merge.

2021-03-12 20:25 UTC, devin-petersohn reviewed
Is it possible to run `black` on the test code?

2021-03-13 03:13 UTC, richardlin047 commented
Reformatted with black, no changes to the test code were needed.

2021-03-15 17:58 UTC, devin-petersohn approved these changes
LGTM, thanks @valerieyip!

2021-03-15 18:02 UTC, merged